inherit_from:
  - https://raw.githubusercontent.com/riboseinc/oss-guides/master/style/.rubocop.yml

AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 120

FrozenStringLiteralComment:
  Enabled: false

Style/FileName:
  Enabled: false

Documentation:
  Enabled: false
