= Citations in AsciiDoc using asciidoctor-bibliography

image:https://img.shields.io/gem/v/asciidoctor-bibliography.svg["Gem Version", link="https://rubygems.org/gems/asciidoctor-bibliography"]
image:https://img.shields.io/travis/riboseinc/asciidoctor-bibliography/master.svg["Build Status", link="https://travis-ci.org/riboseinc/asciidoctor-bibliography"]
image:https://codeclimate.com/github/riboseinc/asciidoctor-bibliography/badges/gpa.svg["Code Climate", link="https://codeclimate.com/github/riboseinc/asciidoctor-bibliography"]

Citations in AsciiDoc using the fantastic http://asciidoctor.org/[asciidoctor].

== Introduction

This gem allows you to add BibTex style Citations to AsciiDoc.

== Installation

Add this line to your Gemfile:

[source,ruby]
----
gem "asciidoctor-bibliography"
----

And then execute:

[source,console]
----
$ bundle install
----

Or install it yourself as:

[source,console]
----
$ gem install asciidoctor-bibliography
----

== Configure

In your document header, define the following below the title.

----
= Latex Macros In Bibtex Items
:bibliography-database: first.bib
:bibliography-database: second.bib
:bibliography-style: ieee
----

== Usage

Include asciidoctor-bibliography in your chain:

[source,console]
----
$ asciidoctor -r asciidoctor-bibliography main.adoc
----

Add citation commands within your AsciiDoc:

----
Searching Function (see cite:guo2009[])
----

List out bibliography:

----
bibliography::[]
----

== Example

----
= Latex Macros In Bibtex Items
:bibliography-database: reference.bib
:bibliography-style: ieee

== Contents

This is a paper "Validation and Verificaton of Computer Forensic Software
tools -- Searching Function" (see cite:guo2009[]).

== Bibliography

bibliography::[]
----

== Development

We follow Sandi Metz's Rules for this gem, you can read the
http://robots.thoughtbot.com/post/50655960596/sandi-metz-rules-for-developers[description of the rules here].
All new code should follow these rules. If you make
changes in a file that already violates these rules, you should fix the
violations as part of your contribution.

=== Setup

Clone the repository.

[source,sh]
----
git clone https://github.com/riboseinc/asciidoctor-bibliography
----

Setup your environment.

[source,sh]
----
bin/setup
----

Run the test suite

[source,sh]
----
bin/rspec
----

== Contributing

First, thank you for contributing! We love pull requests from everyone. By
participating in this project, you hereby grant
https://www.ribose.com[Ribose Inc.] the right to grant or transfer an unlimited
number of non exclusive licenses or sub-licenses to third parties, under the
copyright covering the contribution to use the contribution by all means.

Here are a few technical guidelines to follow:

1. Open an https://github.com/riboseinc/asciidoctor-bibliography/issues[issues] to discuss a new feature.
2. Write tests to support your new feature.
3. Make sure the entire test suite passes locally and on CI.
4. Open a Pull Request.
5. https://github.com/thoughtbot/guides/tree/master/protocol/git=write-a-feature[Squash your commits] after receiving feedback.
6. Party!

== Credits

This gem is developed, maintained and funded by
https://www.ribose.com[Ribose Inc.]

== License

The gem is available as open source under the terms of the
http://opensource.org/licenses/MIT[MIT License].

