= Sample of using asciidoctor-bibtex
:bibliography-database: biblio.bib
:bibliography-style: chicago-author-date

New syntax: citet:[Anderson04]

New syntax: citet:[Lane12a]+[Lane12b]

New syntax: citet*:[Anderson04]

New syntax: citet*:[Lane12a]+[Lane12b]

New syntax: citealt:[Anderson04]

New syntax: citealt:[Lane12a]+[Lane12b]

New syntax: citealt*:[Anderson04]

New syntax: citealt*:[Lane12a]+[Lane12b]

New syntax: citep:[Anderson04]

New syntax: citep:[Lane12a]+[Lane12b]

New syntax: citep*:[Anderson04]

New syntax: citep*:[Lane12a]+[Lane12b]

New syntax: citealp:[Anderson04]

New syntax: citealp:[Lane12a]+[Lane12b]

New syntax: citealp*:[Anderson04]

New syntax: citealp*:[Lane12a]+[Lane12b]







New syntax: citeauthor:[Anderson04]

New syntax: citeauthor:[Lane12a]+[Lane12b]

New syntax: citeauthor*:[Anderson04]

New syntax: citeauthor*:[Lane12a]+[Lane12b]


New syntax: citeyear:[Anderson04]

New syntax: citeyear:[Lane12a]+[Lane12b]

New syntax: citeyearpar:[Anderson04]
                   
New syntax: citeyearpar:[Lane12a]+[Lane12b]






References can be inserted in lists, too:
See citet*:[Lane12a], whatever.

1. See citealt:[Lane12a].
2. See citealp*:[Lane12b].

Another one: citeyear:[Lane12a].

citeauthor:[Anderson98]

[sect2] 
== Bibliography

bibliography::[]